# Pull & deploy using docker compose

name: "cd deploy"

on:
  #push:
  #  branches:
  #    - main
  #pull_request:
  #workflow_dispatch:
  workflow_call:

jobs:

  deply:
    name: "Deploy to EC2 Production"
    runs-on: self-hosted

    steps:
    
      - name: "Checkout the code"
        uses: actions/checkout@v4
          
      - name: "deploy with docker compose"
        run: |
          cat <<EOF > .env
          export DB_ROOT_PASS="${{ secrets.DB_ROOT_PASS }}"
          export DB_NAME="${{ secrets.DB_NAME }}"
          export DB_USER="${{ secrets.DB_USER }}"
          export DB_PASS="${{ secrets.DB_PASS }}"
          export WEBSITE_ADDRESS="${{ secrets.WEBSITE_ADDRESS }}"
          export PROTOCOL="${{ secrets.PROTOCOL }}"
          EOF

          chmod 600 .env

          ###### deploy with docker compose"
          
          docker compose down && docker compose up -d --force-recreate --pull always
        
