# DevSecOps End To End Pipeline

name: "ci/cd pipeline"

on:
  #push:
  #  branches:
  #    - main
  #pull_request:
  workflow_dispatch:

jobs: 
  # setup runner
  setup-runner:
    uses: ./.github/workflows/setup-runner.yml

  # CI 
  secret-scan:
    uses: ./.github/workflows/ci-secret-scan.yml
    
  shell-script-scan:
    uses: ./.github/workflows/ci-shell-script-scan.yml
    
  dockerfile-scan:
    uses: ./.github/workflows/ci-dockerfile-scan.yml
   
  build-scan-push:
    needs: [setup-runner, secret-scan, shell-script-scan, dockerfile-scan]
    uses: ./.github/workflows/ci-build-scan-push.yml
    secrets: inherit

  # CD
  
  deploy:
    needs: [build-scan-push]
    uses: ./.github/workflows/cd-deploy.yml
    secrets: inherit
