#secret-scan → Gitleaks + TruffleHog # (secrets in code/history)
name: "ci secret scan"

on:
  #push:
  #  branches:
  #    - main
  #pull_request:
  #workflow_dispatch:
  workflow_call:

  
jobs:

  secret-scan:
    name: "secret scan using Gitleaks and TruffleHog"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout the full history"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          

      - name: "Gitleaks — scan for secrets in code and git history"
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: "Secret Scanning using TruffleHog scan"
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          extra_args: --only-verified
