# Backup to S3 

name: "Ops / S3 Backup"

on:
  #push:
  #  branches:
  #    - main
  #pull_request:
  schedule:
    - cron: '50 4 * * *'
  workflow_dispatch:
  

jobs:

  backup:
    name: "Backup to S3"
    runs-on: self-hosted

    steps:
      - name: "Checkout source"
        uses: actions/checkout@v4
        
      - name: "Run lms-backup.sh"
        run: |
          export DB_ROOT_PASS="${{ secrets.DB_ROOT_PASS }}"
          export DB_NAME="${{ secrets.DB_NAME }}"
          export DB_USER="${{ secrets.DB_USER }}"
          export DB_PASS="${{ secrets.DB_PASS }}"
          export WEBSITE_ADDRESS="${{ secrets.WEBSITE_ADDRESS }}"
          export PROTOCOL="${{ secrets.PROTOCOL }}"
          
          export S3_BUCKET="${{ secrets.S3_BUCKET }}"
          export S3_PREFIX="${{ secrets.S3_PREFIX }}"
          export S3_KEEP_LAST="${{ secrets.S3_KEEP_LAST }}"
          
          export LOCAL_KEEP_LAST="3"
          chmod +x scripts/lms-backup.sh
          sudo -E ./scripts/lms-backup.sh

          
