# Backup to S3 

name: "Ops / S3 Backup"

on:
  #push:
  #  branches:
  #    - main
  #pull_request:
  workflow_dispatch:
  

jobs:

  backup:
    name: "Backup to S3"
    runs-on: self-hosted

    steps:
      - name: "Checkout source"
        uses: actions/checkout@v4
        
      - name: "Run lms-backup.sh"
        run: |
          cat <<EOF > .env
          DB_ROOT_PASS="${{ secrets.DB_ROOT_PASS }}"
          DB_NAME="${{ secrets.DB_NAME }}"
          DB_USER="${{ secrets.DB_USER }}"
          DB_PASS="${{ secrets.DB_PASS }}"
          WEBSITE_ADDRESS="${{ secrets.WEBSITE_ADDRESS }}"
          PROTOCOL="${{ secrets.PROTOCOL }}"
          S3_BUCKET="${{ secrets.S3_BUCKET }}"
          S3_PREFIX="${{ secrets.S3_PREFIX }}"
          S3_KEEP_LAST="${{ secrets.S3_KEEP_LAST }}"
          LOCAL_KEEP_LAST="3"
          EOF

          mv .env /home/ubuntu/.env
          mv scripts/lms-backup.sh /home/ubuntu/lms-backup.sh
          
          chmod 600 /home/ubuntu/.env
          chmod +x /home/ubuntu/lms-backup.sh
          
          sudo -E ./home/ubuntu/lms-backup.sh
          

          
