# Restore from s3

name: "Ops / S3 Restore"

on:
  #push:
  #  branches:
  #    - main
  #pull_request:
  workflow_dispatch:

jobs:

  restore:
    name: "Restore from S3"
    runs-on: self-hosted
    
    steps:
      - name: "Checkout source"
        uses: actions/checkout@v4

      - name: "Download backup from S3 and restore"
        run: |
          export IMAGE_TAG="${{ github.sha }}"
          export IMAGE_TAG="${IMAGE_TAG::7}"
          
          export S3_BUCKET="${{ secrets.S3_BUCKET }}"
          export S3_PREFIX="${{ secrets.S3_PREFIX }}"
          export S3_KEEP_LAST="${{ secrets.S3_KEEP_LAST }}"
          
          LATEST_FILE=$(aws s3 ls s3://${{ secrets.S3_BUCKET }}/${{ secrets.S3_PREFIX }}/ | sort | tail -n 1 | awk '{print $4}')
          aws s3 cp s3://${{ secrets.S3_BUCKET }}/${{ secrets.S3_PREFIX }}/$LATEST_FILE .
          
          sudo mv $LATEST_FILE /opt/
          sudo tar -xzf /opt/$LATEST_FILE -C /opt/
          
          ###### Run lms-restore.sh 
          
          export DB_ROOT_PASS="${{ secrets.DB_ROOT_PASS }}"
          export DB_NAME="${{ secrets.DB_NAME }}"
          export DB_USER="${{ secrets.DB_USER }}"
          export DB_PASS="${{ secrets.DB_PASS }}"
          export WEBSITE_ADDRESS="${{ secrets.WEBSITE_ADDRESS }}"
          export PROTOCOL="${{ secrets.PROTOCOL }}"
          export LOCAL_KEEP_LAST="3"
          export REDIS_HOST="${{ secrets.REDIS_HOST }}"
          export REDIS_PASSWORD="${{ secrets.REDIS_PASSWORD }}"
          
          FOLDER=${LATEST_FILE#lms-backup-}
          FOLDER=${FOLDER%.tar.gz}
          
          chmod +x scripts/lms-restore.sh
          sudo -E ./scripts/lms-restore.sh /opt/$FOLDER
          
